version: 2

- formats:
  - pdf

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

python:
  version: 3.7
  install:
    - requirements: docs/requirements-rtd.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: setuptools
      path: .
  system_packages: true
